services:    
    smart_core_session.handler:
        class: SmartCore\Bundle\SessionBundle\Handler\Orm
        arguments: [@doctrine.orm.entity_manager, @service_container]
    
    smart_core_session.user_id_listener:
        class: SmartCore\Bundle\SessionBundle\Listener\UserId
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: updateSessionUserId }
